server {
    listen       80;
    server_name  localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # 解决单页应用刷新 404 的问题
        try_files $uri $uri/ /index.html;
    }
}